2025-09-25 21:07:55 | ERROR | (pymysql.err.ProgrammingError) (1146, "Table 'ppabe.Anios' doesn't exist")
[SQL: SELECT `Anios`.id AS `Anios_id`, `Anios`.creador AS `Anios_creador`, `Anios`.modificador AS `Anios_modificador`, `Anios`.`fCreacion` AS `Anios_fCreacion`, `Anios`.`fModificacion` AS `Anios_fModificacion`, `Anios`.deleted AS `Anios_deleted` 
FROM `Anios`]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-09-25 21:07:55 | ERROR | Traceback (most recent call last):
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1961, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/default.py", line 944, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
    ~~~~~~~~~~^^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
    ~~~~~~~~~~~^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'ppabe.Anios' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/src/routes/public.py", line 15, in get_anios
    anios = AnioServicie.get_all()
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/src/services/anio_service.py", line 7, in get_all
    anios = Anio.query.all()
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/orm/query.py", line 2704, in all
    return self._iter().all()  # type: ignore
           ~~~~~~~~~~^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/orm/query.py", line 2857, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
        params,
        ^^^^^^^
        execution_options={"_sa_orm_load_options": self.load_options},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/orm/context.py", line 306, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/sql/elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1840, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1980, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 2349, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/base.py", line 1961, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/sqlalchemy/engine/default.py", line 944, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
    ~~~~~~~~~~^^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
    ~~~~~~~~~~~^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/bat-e404/Escritorio/Desarrollo/03 Proyectos de estudio/Backend/Python/Checar/PPABE-Backend-PyService/venv/lib64/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'ppabe.Anios' doesn't exist")
[SQL: SELECT `Anios`.id AS `Anios_id`, `Anios`.creador AS `Anios_creador`, `Anios`.modificador AS `Anios_modificador`, `Anios`.`fCreacion` AS `Anios_fCreacion`, `Anios`.`fModificacion` AS `Anios_fModificacion`, `Anios`.deleted AS `Anios_deleted` 
FROM `Anios`]
(Background on this error at: https://sqlalche.me/e/20/f405)

2025-09-25 21:08:21 | INFO | [{'id': 2024, 'creador': '15955ba3-61cf-11f0-b73a-c4346b72f0ba', 'modificador': '15955ba3-61cf-11f0-b73a-c4346b72f0ba', 'fCreacion': datetime.datetime(2025, 8, 5, 15, 9, 4), 'fModificacion': datetime.datetime(2025, 8, 5, 15, 9, 4), 'deleted': '0'}, {'id': 2025, 'creador': '15955ba3-61cf-11f0-b73a-c4346b72f0ba', 'modificador': '15955ba3-61cf-11f0-b73a-c4346b72f0ba', 'fCreacion': datetime.datetime(2025, 8, 9, 17, 5, 19), 'fModificacion': datetime.datetime(2025, 8, 9, 17, 5, 19), 'deleted': '0'}]
